### ISSUE TITLE
Add first draft of materials for Coffea-Casa and Compute Infrastructure session

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/us-atlas-idap-training-2024#1]
## Description

Have @oshadura add a first draft of the materials to be taught at the 2024 [US ATLAS / IRIS-HEP Analysis Software Training Event](https://indico.cern.ch/event/1376945/) by Monday, 15 July 2024 in a pull request to this repo.

## Training event session

* Indico:
   - [Coffea-Casa and Compute Infrastructure Introduction](https://indico.cern.ch/event/1376945/contributions/6028274/)
   - [Coffea-Casa and Compute Infrastructure](https://indico.cern.ch/event/1376945/contributions/6040545/)
* Date: 18 July, 2024
* Lead instructor: @oshadura 

## Reference material

* [Coffea-Casa and the Compute Infrastructure](https://indico.cern.ch/event/1383972/contributions/5825300/) from the June 2024 US CMS / IRIS-HEP training event.

## Scope

The target audience at the training event will be similar to the US CMS / IRIS-HEP training event of being ATLAS Ph.D. students.

The goal is to use the UChicago Coffea-casa deployment as the students will be US ATLAS members and this would be the best choice to support their credentials while also having access to Coffea-casa, unless @oshadura has alternative suggestions.

**Comment by oshadura** [comment]
Hi Matthew! I think the schedule was not updated, since we decided that the slot should be divided into 2 parts: one short intro with quick user onboarding at facility and another slot that will be 30 minutes long before Lindsey's contribution. This contribution will include some basic dask (dask delayes and futures) and dask distributed notebooks + some extra info on how to use dask at facility.)

**Comment by oshadura** [comment]
cc: @alexander-held with whom we had a chat today about how to improve schedule

**Comment by matthewfeickert** [comment]
> I think the schedule was not updated, since we decided that the slot should be divided into 2 parts: one short intro with quick user onboarding at facility and another slot that will be 30 minutes long before Lindsey's contribution.

@oshadura Okay, I had got the impression when we talked at the US CMS training event that you wanted to have it all in one session. Is it necessary to have it in two sections with the second _directly_ before https://github.com/iris-hep/us-atlas-idap-training-2024/issues/4? If not, then as https://github.com/iris-hep/us-atlas-idap-training-2024/issues/2 will have time constraints from Jim to not begin before 10:00 then it would be perferable to have you cover everything that you want in a single session with as much time as you need.

> we had a chat today about how to improve schedule

@oshadura @alexander-held Can you both share your schedule revisions on the `#usatlas-uscms-summer2024-events` IRIS-HEP Slack channel?

**Comment by oshadura** [comment]
From the USCMS event, it was clear that it was a wrong move to start with the session where participants did not understand anything about dask, facility, and why we need scaling. Since Jim doesn't use facility for his piece, the logical place will be start before or after Lindsey. If I am before Lindsey talk and he will do the same training as we did on USCMS, I believe my introduction will be a much smoother intro to his talk.

**Comment by matthewfeickert** [comment]
@oshadura The 45 minute "Coffea-Casa and Compute Infrastructure" session at the start has now been split into these two sessions:

* [Coffea-Casa and Compute Infrastructure Introduction](https://indico.cern.ch/event/1376945/contributions/6028274/) (15 minutes)
* [Coffea-Casa and Compute Infrastructure](https://indico.cern.ch/event/1376945/contributions/6040545/) (30 minutes) just before #4

I think I've given you admin controls on the Indico, so if you'd like revisions to the time durations for either session feel free to revise them for whatever is best (or let me know and I can do it too). If you'd like better session names feel free to revise them too. :+1:
